services:

  postgres:
    image: postgres:16
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: incidentdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d incidentdb"]
      interval: 5s
      timeout: 3s
      retries: 10

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7
    container_name: redis-cache
    restart: always
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10

  logservice:
    build:
      context: ./services/LogService
    container_name: logservice
    restart: always
    ports:
      - "5108:8080"
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    environment:
      ASPNETCORE_URLS: http://+:8080
      ConnectionStrings__DefaultConnection: Host=postgres;Port=5432;Database=incidentdb;Username=admin;Password=admin123
      RabbitMQ__Host: rabbitmq

  incidentservice:
    build:
      context: ./services/IncidentService
    container_name: incidentservice
    restart: always
    ports:
      - "5018:8080"
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy
      aianalysisservice:
        condition: service_started
    environment:
      ASPNETCORE_URLS: http://+:8080
      RabbitMQ__Host: rabbitmq
      Redis__Connection: redis:6379
      AIService__Url: http://aianalysisservice:8080

  aianalysisservice:
    build:
      context: ./services/AIAnalysisService
    container_name: aianalysisservice
    restart: always
    ports:
      - "5247:8080"
    environment:
      ASPNETCORE_URLS: http://+:8080

  apigateway:
    build:
      context: ./services/ApiGateway
    container_name: apigateway
    restart: always
    ports:
      - "5000:8080"
    depends_on:
      - logservice
      - incidentservice
    environment:
      ASPNETCORE_URLS: http://+:8080

  aiinferenceservice:
    build:
      context: ./services/AIInferenceService
    container_name: aiinferenceservice
    restart: always
    ports:
      - "8000:8000"
    environment:
      OPENROUTER_API_KEY: ${OPENROUTER_API_KEY}

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - apigateway

volumes:
  postgres_data: